name: glpk
description: A simple command-line application.
version: 0.2.0-nullsafety.2
homepage: https://github.com/TimWhiting/glpk
environment:
  sdk: ">=2.12.0-264.1.dev <3.0.0"

dependencies:
  js: ^0.6.3
  ffi: ^1.0.0
  petitparser: ">=3.1.0 < 4.0.0-nullsafety.10"

dev_dependencies:
  test: any
  ffigen: ^2.0.0

ffigen:
  output: "lib/src/bindings/ffi.dart"
  headers:
    entry-points:
      - "/usr/local/include/glpk.h"
    include-directives:
      - "/usr/local/include/*"
  structs:
    rename:
      "__(.*)": "$1"
  name: "GLPK_C"
  description: "Bindings to GLPK (http://www.gnu.org/software/glpk/)"
  array-workaround: true
  sort: true
